spring:
  jackson:
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd hh:mm:ss
  messages:
    basename: 仓库管理系统
  datasource:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      connection-test-query: SELECT 1
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.219.68:3307/software_class?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8


  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML5


#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.seehin.softwareclass.entity
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8088